#!/bin/bash
#      _          _ _
#   ___| |__   ___| (_) ___  _   _ ___
#  / _ \ '_ \ / _ \ | |/ _ \| | | / __|
# |  __/ |_) |  __/ | | (_) | |_| \__ \
#  \___|_.__/ \___|_|_|\___/ \__,_|___/
# https://github.com/ebelious
#
# This is for creating a loading animation when running a process
#

# Different animations
#spinn=( '\' '|' '/' '-' )
spinn[0]='-'
spinn[1]='\\'
spinn[2]='|'
spinn[3]='/'
#spinn=( Ooooo oOooo ooOoo oooOo ooooO )
#spinn=( '#....' '.#...' '..#..' '...#.' '....#' )
#spinn=( '>____' '_>___' '__>__' '___>_' '____>' )
HOSTED=$(grep Hosted speedtest.tmp)
DL=$(grep Download speedtest.tmp | awk '{print $2 $3}')
UL=$(grep Upload speedtest.tmp | awk '{print $2 $3}')
clear

process(){
 spin &
 pid=$!
  speedtest-cli > speedtest.tmp
  kill $pid
clear
echo
echo -e "$HOSTED"
echo -e "\e[0;36mDownload:\e[0m $DL"
echo -e "\e[0;32mUpload:\e[0m $UL"
}

spin(){
  while [ 1 ]
  do
    for i in "${spinn[@]}"
    do
      echo -ne "\r\e[0;32m[\e[0m\e[0;36m$i\e[0;32m]\e[0m Testing Connection"
      sleep 0.2
    done
  done
}

process
